type = "card"
title = "Projects"
description = "Projects I have received."

[[items]]
title = "Example Award"
subtitle = "Organization"
date = "2025"
content = "Description of the award."

[[items]]
title = "Example Award"
subtitle = "Organization"
date = "2024"
content = "Description of the award."

[[items]]
title = "Example Award"
subtitle = "Organization"
date = "2023"
content = "Description of the award."

[[items]]
title = "Example Award"
subtitle = "Organization"
date = "2022"
content = "Description of the award."
